function A=uniform(a,c,m,s) %Generate an uniform distribution function,a¡Bc¡Bm¡Bs represent LCGs multiplier¡Bincrement¡Bmodulus¡Binitial value
A=zeros(65536,1);%Record 65536 random numbers generated by matrix
i=1;
while i<=65536
s=mod((a*s+c),m);
x=s/m;%Generating 0-1 uniformly distributed random numbers
A(i,1)=x;
i=i+1;
end
end

